name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Fetch Go dependencies
        run: |
          go mod tidy
          go mod download
          ls -l go.mod go.sum || echo "go.mod or go.sum missing"

      - name: Set up Docker (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo systemctl start docker
          docker --version

      - name: Set up Docker (macOS)
        if: matrix.os == 'macos-latest'
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Set up Docker (Windows)
        if: matrix.os == 'windows-latest'
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Verify Docker Installation
        run: docker --version

      - name: Verify Docker is operational
        run: |
          docker info
          docker ps