name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Fetch Go dependencies
        run: |
          go mod tidy
          go mod download
          ls -l go.mod go.sum || echo "go.mod or go.sum missing"

      # Linux setup (Docker is pre-installed)
      - name: Start Docker (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo systemctl start docker
          sudo chmod 666 /var/run/docker.sock

      # macOS setup
      - name: Install colima for Docker (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install docker
          brew install colima
          colima start --runtime docker
          ln -s ~/.colima/default/docker.sock /var/run/docker.sock

      # Windows setup
      - name: Install Docker (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install docker-cli -y
          choco install docker-machine -y
          docker-machine create --driver hyperv default
          docker-machine env default | Invoke-Expression
        shell: powershell

      - name: Verify Docker
        run: |
          docker --version
          docker info
          docker ps