name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Docker (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          # Remove conflicting packages
          sudo apt-get remove -y docker docker-engine docker.io containerd runc containerd.io || true
          # Clean apt cache and fix broken packages
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get install -y --fix-missing
          # Install dependencies for Docker
          sudo apt-get install -y ca-certificates curl gnupg lsb-release
          # Add Docker's official GPG key
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          # Set up Docker repository
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          # Update apt and install Docker
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          # Start Docker and add user to docker group
          sudo systemctl start docker
          sudo usermod -aG docker $USER
          docker --version

      - name: Set up Docker (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install colima
          brew services start colima
      - name: Verify Docker (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          docker --version
          docker ps

      - name: Install Docker (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install docker-desktop
          docker --version
        shell: powershell

      - name: Run setup-dependencies script
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            powershell -File scripts/setup-dependencies.ps1
          else
            chmod +x scripts/setup-dependencies.sh
            ./scripts/setup-dependencies.sh
          fi
        shell: bash

      - name: Run unit tests
        run: go test ./internal/... -v

      - name: Run integration tests
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            powershell -File scripts/test-integration.ps1
          else
            chmod +x scripts/test-integration.sh
            ./scripts/test-integration.sh
          fi
        shell: bash

      - name: Build
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh