name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Fetch Go dependencies
        run: |
          go mod tidy
          go mod download
          ls -l go.mod go.sum || echo "go.mod or go.sum missing"

      # Linux setup
      - name: Setup Docker (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo systemctl start docker
          sudo chmod 666 /var/run/docker.sock

      # macOS and Windows setup using official Docker actions
      - name: Set up Docker Buildx
        if: matrix.os != 'ubuntu-latest'
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Verify Docker
        run: |
          docker --version
          docker buildx version
          docker buildx inspect