name: Build and Release

on:
  push:
    branches: [ cli-development ]
#    tags:
#      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
          path: kindctl

      - name: Change to project directory
        run: cd kindctl
        shell: bash

      - name: Debug directory contents
        run: |
          pwd
          ls -la
          find . -type f
        shell: bash

      - name: Verify go.mod and main.go
        run: |
          if [ ! -f go.mod ]; then
            echo "Error: go.mod not found"
            exit 1
          fi
          if [ ! -f cmd/kindctl/main.go ]; then
            echo "Error: cmd/kindctl/main.go not found"
            exit 1
          fi
          echo "go.mod and cmd/kindctl/main.go found"
        shell: bash

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binary
        run: |
          case "${{ matrix.os }}" in
            windows-latest)
              BINARY="kindctl-windows-${{ matrix.arch }}.exe"
              GOOS="windows"
              ;;
            macos-latest)
              BINARY="kindctl-darwin-${{ matrix.arch }}"
              GOOS="darwin"
              ;;
            ubuntu-latest)
              BINARY="kindctl-linux-${{ matrix.arch }}"
              GOOS="linux"
              ;;
          esac
          mkdir -p bin
          GOARCH=${{ matrix.arch }} go build -o bin/$BINARY ./cmd/kindctl
        env:
          CGO_ENABLED: 0
        working-directory: kindctl
        shell: bash

      - name: Create release directory
        run: |
          mkdir -p releases/download/v0.0.0
          mv bin/* releases/download/v0.0.0/
        shell: bash

      - name: Copy install scripts
        run: |
          cp scripts/install.sh releases/download/v0.0.0/
          cp scripts/install.ps1 releases/download/v0.0.0/
        shell: bash

      - name: Commit release assets
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add releases/download/v0.0.0
          git commit -m "Add release assets for v0.0.0" || echo "No changes to commit"
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/download/v0.0.0/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}