name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
          path: kindctl

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Get tag version
        id: tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        working-directory: kindctl
        shell: bash

      - name: Install zip on Windows
        if: matrix.os == 'windows-latest'
        run: choco install zip
        shell: powershell

      - name: Build and package binary
        run: |
          set -e
          
          case "${{ matrix.os }}" in
            windows-latest)
              EXT=".exe"
              OS_NAME="windows"
              ;;
            macos-latest)
              EXT=""
              OS_NAME="darwin"
              ;;
            ubuntu-latest)
              EXT=""
              OS_NAME="linux"
              ;;
          esac
          
          BINARY="kindctl-${OS_NAME}-${{ matrix.arch }}${EXT}"
          ARCHIVE="${BINARY%.*}"
          
          echo "🛠 Building $BINARY..."
          mkdir -p bin
          GOARCH=${{ matrix.arch }} GOOS=$OS_NAME CGO_ENABLED=0 go build -ldflags "-X main.version=${{ env.VERSION }}" -o bin/$BINARY ./cmd/kindctl
          
          echo "📦 Packaging $ARCHIVE..."
          cd bin
          if [[ "$EXT" == ".exe" ]]; then
            zip "${ARCHIVE}.zip" "$BINARY"
          else
            tar -czvf "${ARCHIVE}.tar.gz" "$BINARY"
          fi
          cd ..
          
          echo "📁 Moving archive to release directory..."
          mkdir -p releases/download/${{ env.VERSION }}
          mv bin/*.zip bin/*.tar.gz releases/download/${{ env.VERSION }}/ || true
          ls -la releases/download/${{ env.VERSION }}/
        working-directory: kindctl
        shell: bash

      - name: Verify installer works
        run: |
          echo "🔍 Verifying binary functionality..."
          
          case "${{ matrix.os }}" in
            windows-latest)
              if [ "${{ matrix.arch }}" == "arm64" ]; then
                BINARY="kindctl-windows-arm64.exe"
              else
                BINARY="kindctl-windows-amd64.exe"
              GOOS="windows"
              fi
              ;;
            macos-latest)
              if [ "${{ matrix.arch }}" == "arm64" ]; then
                BINARY="kindctl-darwin-arm64"
              else
                BINARY="kindctl-darwin-amd64"
              fi
              GOOS="darwin"
              ;;
            ubuntu-latest)
              if [ "${{ matrix.arch }}" == "arm64" ]; then
                BINARY="kindctl-linux-arm64"
              else
                BINARY="kindctl-linux-amd64"
              fi
              GOOS="linux"
              ;;
          esac
          
          if [[ "$(uname -m)" != "aarch64" && "$BINARY" == *"linux-arm64"* ]]; then
            echo "⚠️ Skipping execution of $BINARY on amd64 runner"
          else
            echo "▶ Running ./bin/$BINARY --version"
            ./bin/$BINARY --version || (echo "❌ $BINARY --version failed" && exit 1)
        
            echo "▶ Running ./bin/$BINARY --help"
            ./bin/$BINARY --help || (echo "❌ $BINARY --help failed" && exit 1)
        
            echo "✅ $BINARY passed verification."
          fi
        working-directory: kindctl
        shell: bash

      - name: Verify ARM64 build (using Docker for ARM emulation)
        if: matrix.arch == 'arm64'
        run: |
          docker run --rm --platform linux/arm64/v8 -v $PWD:/workspace -w /workspace ubuntu:latest \
            bash -c "./bin/kindctl-linux-arm64 --version"

      - name: Create release directory
        run: |
          mkdir -p releases/download/${{ env.VERSION }}
          mv bin/* releases/download/${{ env.VERSION }}/
        working-directory: kindctl
        shell: bash

      - name: Copy install scripts
        run: |
          cp scripts/install.sh releases/download/${{ env.VERSION }}/
          cp scripts/install.ps1 releases/download/${{ env.VERSION }}/
        working-directory: kindctl
        shell: bash

      - name: Commit release assets
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add releases/download/${{ env.VERSION }}
          git commit -m "Add release assets for ${{ env.VERSION }}" || echo "No changes to commit"
          git pull --rebase origin "$GITHUB_REF_NAME"
          git push origin "$GITHUB_REF_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        working-directory: kindctl
        shell: bash