name: Build and Release

on:
  push:
    branches: [ cli-development ]
#    tags:
#      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
          path: kindctl

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binary
        run: |
          set -ex
          case "${{ matrix.os }}" in
            windows-latest)
              BINARY="kindctl-windows-${{ matrix.arch }}.exe"
              GOOS="windows"
              ;;
            macos-latest)
              BINARY="kindctl-darwin-${{ matrix.arch }}"
              GOOS="darwin"
              ;;
            ubuntu-latest)
              BINARY="kindctl-linux-${{ matrix.arch }}"
              GOOS="linux"
              ;;
          esac
          mkdir -p bin
          GOOS=$GOOS GOARCH=${{ matrix.arch }} go build -o bin/$BINARY ./cmd/kindctl
        env:
          CGO_ENABLED: 0
        working-directory: kindctl
        shell: bash

      - name: Debug project files
        run: |
          ls -la
          ls -la cmd/kindctl
          cat cmd/kindctl/main.go
        working-directory: kindctl
        shell: bash

      - name: Create release directory
        run: |
          mkdir -p releases/download/v0.0.0
          mv bin/* releases/download/v0.0.0/
        working-directory: kindctl
        shell: bash

      - name: Copy install scripts
        run: |
          cp scripts/install.sh releases/download/v0.0.0/
          cp scripts/install.ps1 releases/download/v0.0.0/
        working-directory: kindctl
        shell: bash

      - name: Commit release assets
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add releases/download/v0.0.0
          git commit -m "Add release assets for v0.0.0" || echo "No changes to commit"
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        shell: bash