name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo usermod -aG docker $USER

      - name: Build binaries
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/kindctl-linux-amd64
            bin/kindctl-linux-arm64
            bin/kindctl-darwin-amd64
            bin/kindctl-darwin-arm64
            bin/kindctl-windows-amd64.exe
            bin/kindctl-windows-arm64.exe
            scripts/install.sh
            scripts/install.ps1
            scripts/setup-dependencies.sh
            scripts/setup-dependencies.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}